
FROM node:10.15.3

#inside the container, in root filesystem
RUN mkdir /simpsons

#becomes active working directory
WORKDIR /simpsons

#copies into active working directory. for development, copy everything.
COPY package.json /simpsons

#install dependencies
RUN npm i

COPY . /simpsons

CMD ["npm", "run", "start"]

EXPOSE 8080
