FROM node:10.15.3 as builder

#inside the container, in root filesystem
RUN mkdir /simpsons

#becomes active working directory
WORKDIR /simpsons

#copies into active working directory. for development, copy everything.
COPY . .

#install dependencies
RUN npm i

RUN npm rebuild node-sass
RUN npm run build


# Copy built app into nginx container
FROM localhost:5000/waf_web:latest

COPY --from=builder /simpsons/public /usr/local/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

