# don't forget to push

FROM node:6.11.4 as builder

RUN mkdir /simpsons

WORKDIR /simpsons

COPY package.json /simpsons

RUN npm i
RUN npm rebuild node-sass

COPY . /simpsons

FROM localhost:5000/nginx_waf
COPY --from=builder /simpsons/public /usr/local/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
