FROM node:6.11.4 as builder

RUN mkdir /simpsons

WORKDIR /simpsons

COPY package.json /simpsons

RUN npm i
RUN npm rebuild node-sass

COPY . /simpsons

RUN npm run build

FROM nginx:latest
COPY --from=builder /simpsons/public /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]