const characters = [
    {
        firstName: 'NED',
        lastName: 'FLANDERS',
        fullName: 'NED FLANDERS',
        imageUrl: 'https://rebrand.ly/ffad',
        guessed: false,
    },
    {
        firstName: 'LISA',
        lastName: 'SIMPSON',
        fullName: 'LISA SIMPSON',
        imageUrl: 'https://rebrand.ly/25f6',
        guessed: false,

    },
    {
        firstName: 'CARL',
        lastName: 'CARLSON',
        fullName: 'CARL CARLSON',
        imageUrl: 'https://rebrand.ly/2267',
        guessed: false,
    },
    {
        firstName: 'RALPH',
        lastName: 'WIGGUM',
        fullName: 'RALPH WIGGUM',
        imageUrl: 'https://rebrand.ly/33c3',
        guessed: false,
    },
    {
        firstName: 'APU',
        lastName: 'NAHASAPEEMAPETILON',
        fullName: 'APU NAHASAPEEMAPETILON',
        imageUrl: 'https://rebrand.ly/b796',
        guessed: false,
    },
    {
        firstName: 'HOMER',
        lastName: 'SIMPSON',
        fullName: 'HOMER SIMPSON',
        imageUrl: 'https://rebrand.ly/e71e',
        guessed: false,
    },
    {
        firstName: 'LENNY',
        lastName: 'LEONARD',
        fullName: 'LENNY LEONARD',
        imageUrl: 'https://rebrand.ly/6fe8',
        guessed: false,
    },
    {
        firstName: 'MOE',
        lastName: 'SYZLAK',
        fullName: 'MOE SYZLAK',
        imageUrl: 'https://rebrand.ly/efbb',
        guessed: false,
    },
    {
        firstName: 'MARGE',
        lastName: 'SIMPSON',
        fullName: 'MARGE SIMPSON',
        imageUrl: 'https://rebrand.ly/7f6f',
        guessed: false,
    },
    {
        firstName: 'PATTY',
        lastName: 'BOUVIER',
        fullName: 'PATTY BOUVIER',
        imageUrl: 'https://rebrand.ly/f785',
        guessed: false,
    },
    {
        firstName: 'BART',
        lastName: 'SIMPSON',
        fullName: 'BART SIMPSON',
        imageUrl: 'https://rebrand.ly/myacc8c76',
        guessed: false,
    },
    {
        firstName: 'MAGGIE',
        lastName: 'SIMPSON',
        fullName: 'MAGGIE SIMPSON',
        imageUrl: 'https://rebrand.ly/4745',
        guessed: false,
    },
    {
        firstName: 'KODOS',
        fullName: 'KODOS',
        imageUrl: 'https://rebrand.ly/6689',
        guessed: false,
    },
    {
        firstName: 'AGNES',
        lastName: 'SKINNER',
        fullName: 'AGNES SKINNER',
        imageUrl: 'https://rebrand.ly/c33f',
        guessed: false,
    },
    {
        firstName: 'MANJULA',
        lastName: 'NAHASAPEEMAPETILON',
        fullName: 'MANJULA NAHASAPEEMAPETILON',
        imageUrl: 'https://rebrand.ly/7ycf',
        guessed: false,
    },
    {
        firstName: 'ROD',
        lastName: 'FLANDERS',
        fullName: 'ROD FLANDERS',
        imageUrl: 'https://rebrand.ly/df60',
        guessed: false,
    },
    {
        firstName: 'EDNA',
        lastName: 'FLANDERS',
        fullName: 'EDNA FLANDERS',
        imageUrl: 'https://rebrand.ly/08fd',
        guessed: false,
    },
    {
        firstName: 'KIRK',
        lastName: 'VAN HOUTEN',
        fullName: 'KIRK VAN HOUTEN',
        imageUrl: 'https://rebrand.ly/950i',
        guessed: false,
    }
    
]

export default characters;